//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cgm.Ecoupon.Infrastructure.Persistence.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAccessRight
    {
        public System.Guid Id { get; set; }
        public System.Guid UserId { get; set; }
        public System.Guid MenuId { get; set; }
        public bool AddFlag { get; set; }
        public bool UpdateFlag { get; set; }
        public bool DeleteFlag { get; set; }
        public bool UnDeleteFlag { get; set; }
        public bool ViewFlag { get; set; }
        public bool PrintFlag { get; set; }
        public bool ExportFlag { get; set; }
        public bool ImportFlag { get; set; }
        public bool IsActive { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual Menu Menu { get; set; }
        public virtual User User { get; set; }
    }
}
