//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cgm.Ecoupon.Infrastructure.Persistence.Data
{
    using System;
    
    public partial class GetOkDebitWalletNumberDetail_Result
    {
        public string OkDebitWalletNumber { get; set; }
        public string Division { get; set; }
        public string District { get; set; }
        public string Township { get; set; }
        public string City { get; set; }
        public string ProductGroup { get; set; }
        public string Branch { get; set; }
        public int SafetyCashierCount { get; set; }
        public string AdvanceMerchantNumber { get; set; }
        public string CashbackSetting { get; set; }
        public string OfferAutoLoad { get; set; }
        public string Status { get; set; }
        public Nullable<double> AutoPayDiscount { get; set; }
        public Nullable<double> AutoPayFixed { get; set; }
        public Nullable<double> AutoPayRatio { get; set; }
        public int CashbackOpeningAmount { get; set; }
        public int TransferMainToCashbankAmount { get; set; }
        public Nullable<double> CashbackAmount { get; set; }
        public int CashbackClosingAmount { get; set; }
        public System.DateTime DateTime { get; set; }
    }
}
