//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cgm.Ecoupon.Infrastructure.Persistence.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TownShip
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TownShip()
        {
            this.BranchDetails = new HashSet<BranchDetail>();
            this.Cities = new HashSet<City>();
            this.Districts = new HashSet<District>();
            this.OfferAutoPayDiscountDetails = new HashSet<OfferAutoPayDiscountDetail>();
            this.OfferConditionalMappingLocationDetails = new HashSet<OfferConditionalMappingLocationDetail>();
            this.OfferConfigurations = new HashSet<OfferConfiguration>();
            this.OfferDisplayLocationDetails = new HashSet<OfferDisplayLocationDetail>();
        }
    
        public System.Guid ID { get; set; }
        public string Name { get; set; }
        public string BurmeseName { get; set; }
        public Nullable<System.Guid> DivisionID { get; set; }
        public string Code { get; set; }
        public bool Is_Active { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<System.DateTime> Updated_Date { get; set; }
        public string NrcCode { get; set; }
        public string NrcCodeMyan { get; set; }
        public string BurmeseUniqueCode { get; set; }
        public string NrcCodeTemp { get; set; }
        public string NrcCodeMyanTemp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BranchDetail> BranchDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<City> Cities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<District> Districts { get; set; }
        public virtual Division Division { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OfferAutoPayDiscountDetail> OfferAutoPayDiscountDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OfferConditionalMappingLocationDetail> OfferConditionalMappingLocationDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OfferConfiguration> OfferConfigurations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OfferDisplayLocationDetail> OfferDisplayLocationDetails { get; set; }
    }
}
