//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cgm.Ecoupon.Infrastructure.Persistence.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyAndProductMappingDetail
    {
        public System.Guid Id { get; set; }
        public System.Guid CompanyProductMappingId { get; set; }
        public System.Guid ProductGroupId { get; set; }
        public System.Guid ProductCategoryId { get; set; }
        public System.Guid ProductBrandId { get; set; }
        public System.Guid ProductId { get; set; }
        public bool IsActive { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ProductGroupIds { get; set; }
        public string ProductCategoryIds { get; set; }
        public string ProductBrandIds { get; set; }
    
        public virtual ProductBrandDetail ProductBrandDetail { get; set; }
        public virtual ProductCategoryDetail ProductCategoryDetail { get; set; }
        public virtual ProductDetail ProductDetail { get; set; }
        public virtual ProductGroupDetail ProductGroupDetail { get; set; }
    }
}
