//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cgm.Ecoupon.Infrastructure.Persistence.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class District
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public District()
        {
            this.BranchDetails = new HashSet<BranchDetail>();
            this.OfferAutoPayDiscountDetails = new HashSet<OfferAutoPayDiscountDetail>();
            this.OfferConditionalMappingLocationDetails = new HashSet<OfferConditionalMappingLocationDetail>();
            this.OfferConfigurations = new HashSet<OfferConfiguration>();
            this.OfferDisplayLocationDetails = new HashSet<OfferDisplayLocationDetail>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid TownShipId { get; set; }
        public string Name { get; set; }
        public string BurmeseName { get; set; }
        public string Code { get; set; }
        public bool IsActive { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BranchDetail> BranchDetails { get; set; }
        public virtual TownShip TownShip { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OfferAutoPayDiscountDetail> OfferAutoPayDiscountDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OfferConditionalMappingLocationDetail> OfferConditionalMappingLocationDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OfferConfiguration> OfferConfigurations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OfferDisplayLocationDetail> OfferDisplayLocationDetails { get; set; }
    }
}
