//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cgm.Ecoupon.Infrastructure.Persistence.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EcouponNumber
    {
        public System.Guid Id { get; set; }
        public System.Guid EcouponMetadataId { get; set; }
        public Nullable<System.Guid> EcouponAllocationId { get; set; }
        public int status { get; set; }
        public string EcouponNo { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual EcouponMetadata EcouponMetadata { get; set; }
    }
}
