//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cgm.Ecoupon.Infrastructure.Persistence.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OfferManagementEntities1 : DbContext
    {
        public OfferManagementEntities1()
            : base("name=OfferManagementEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ApprovalRequestDetail> ApprovalRequestDetails { get; set; }
        public virtual DbSet<BranchDetail> BranchDetails { get; set; }
        public virtual DbSet<BranchMobileNumberDetail> BranchMobileNumberDetails { get; set; }
        public virtual DbSet<ChildTransInfo> ChildTransInfoes { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<CompanyAndProductMappingDetail> CompanyAndProductMappingDetails { get; set; }
        public virtual DbSet<CompanyAndProductMappingSummarry> CompanyAndProductMappingSummarries { get; set; }
        public virtual DbSet<CompanyDetail> CompanyDetails { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<District> Districts { get; set; }
        public virtual DbSet<Division> Divisions { get; set; }
        public virtual DbSet<EcouponAllocationDetail> EcouponAllocationDetails { get; set; }
        public virtual DbSet<EcouponMetadata> EcouponMetadatas { get; set; }
        public virtual DbSet<EcouponNumber> EcouponNumbers { get; set; }
        public virtual DbSet<EcouponRedeemInfo> EcouponRedeemInfoes { get; set; }
        public virtual DbSet<MasterTransInfo> MasterTransInfoes { get; set; }
        public virtual DbSet<Menu> Menus { get; set; }
        public virtual DbSet<OfferApprovalSetup> OfferApprovalSetups { get; set; }
        public virtual DbSet<OfferAutoPayDiscountDetail> OfferAutoPayDiscountDetails { get; set; }
        public virtual DbSet<OfferBackendNumber> OfferBackendNumbers { get; set; }
        public virtual DbSet<OfferBlockBranchDetail> OfferBlockBranchDetails { get; set; }
        public virtual DbSet<OfferBlockCustomerDetail> OfferBlockCustomerDetails { get; set; }
        public virtual DbSet<OfferBlockDetail> OfferBlockDetails { get; set; }
        public virtual DbSet<OfferConditiionalMappingBranchDetail> OfferConditiionalMappingBranchDetails { get; set; }
        public virtual DbSet<OfferConditionalMappingCustomerDetail> OfferConditionalMappingCustomerDetails { get; set; }
        public virtual DbSet<OfferConditionalMappingDetail> OfferConditionalMappingDetails { get; set; }
        public virtual DbSet<OfferConditionalMappingLocationDetail> OfferConditionalMappingLocationDetails { get; set; }
        public virtual DbSet<OfferConfiguration> OfferConfigurations { get; set; }
        public virtual DbSet<OfferConfigurationMobileNumberDetail> OfferConfigurationMobileNumberDetails { get; set; }
        public virtual DbSet<OfferDetail> OfferDetails { get; set; }
        public virtual DbSet<OfferDetailsHistory> OfferDetailsHistories { get; set; }
        public virtual DbSet<OfferDisplayAppVersionDetail> OfferDisplayAppVersionDetails { get; set; }
        public virtual DbSet<OfferDisplayAppVersionDetailsHistory> OfferDisplayAppVersionDetailsHistories { get; set; }
        public virtual DbSet<OfferDisplayDetail> OfferDisplayDetails { get; set; }
        public virtual DbSet<OfferDisplayDetailsHistory> OfferDisplayDetailsHistories { get; set; }
        public virtual DbSet<OfferDisplayLocationDetail> OfferDisplayLocationDetails { get; set; }
        public virtual DbSet<OfferDisplayLocationDetailsHistory> OfferDisplayLocationDetailsHistories { get; set; }
        public virtual DbSet<OfferDisplayMappingDetail> OfferDisplayMappingDetails { get; set; }
        public virtual DbSet<OfferDisplayMappingDetailsHistory> OfferDisplayMappingDetailsHistories { get; set; }
        public virtual DbSet<OfferDisplayTelcoDetail> OfferDisplayTelcoDetails { get; set; }
        public virtual DbSet<OfferListingType> OfferListingTypes { get; set; }
        public virtual DbSet<OfferOsDetail> OfferOsDetails { get; set; }
        public virtual DbSet<OfferShemeConfiguration> OfferShemeConfigurations { get; set; }
        public virtual DbSet<OfferShemeConfigurationHistory> OfferShemeConfigurationHistories { get; set; }
        public virtual DbSet<OfferShemeType> OfferShemeTypes { get; set; }
        public virtual DbSet<OfferTermsAndCondition> OfferTermsAndConditions { get; set; }
        public virtual DbSet<OfferTermsAndConditionHistory> OfferTermsAndConditionHistories { get; set; }
        public virtual DbSet<OfferTransactionType> OfferTransactionTypes { get; set; }
        public virtual DbSet<OfferType> OfferTypes { get; set; }
        public virtual DbSet<ProductBrandDetail> ProductBrandDetails { get; set; }
        public virtual DbSet<ProductCategoryDetail> ProductCategoryDetails { get; set; }
        public virtual DbSet<ProductDetail> ProductDetails { get; set; }
        public virtual DbSet<ProductGroupDetail> ProductGroupDetails { get; set; }
        public virtual DbSet<TelcoInfo> TelcoInfoes { get; set; }
        public virtual DbSet<TownShip> TownShips { get; set; }
        public virtual DbSet<UOMMaster> UOMMasters { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserAccessRight> UserAccessRights { get; set; }
        public virtual DbSet<UserOfferTypeDetail> UserOfferTypeDetails { get; set; }
        public virtual DbSet<UserProductGroupDetail> UserProductGroupDetails { get; set; }
        public virtual DbSet<UserType> UserTypes { get; set; }
    }
}
