//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cgm.Ecoupon.Infrastructure.Persistence.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EcouponAllocationDetail
    {
        public System.Guid Id { get; set; }
        public System.Guid EcouponMetadataId { get; set; }
        public System.Guid BranchId { get; set; }
        public bool AllocationType { get; set; }
        public long AllocationQuantity { get; set; }
        public Nullable<double> DiscountPercentage { get; set; }
        public Nullable<System.DateTime> ActivatedDate { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> DeactivatedDate { get; set; }
        public string CreatedBy { get; set; }
        public string ActivatedBy { get; set; }
        public string DeactivatedBy { get; set; }
        public int IsActive { get; set; }
    
        public virtual BranchDetail BranchDetail { get; set; }
        public virtual EcouponMetadata EcouponMetadata { get; set; }
    }
}
