//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cgm.Ecoupon.Infrastructure.Persistence.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EcouponRedeemInfo
    {
        public System.Guid Id { get; set; }
        public string EcouponNo { get; set; }
        public System.Guid EcouponNumberId { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
        public string City { get; set; }
        public string Township { get; set; }
        public string AccountNumber { get; set; }
        public string District { get; set; }
        public string Division { get; set; }
    
        public virtual EcouponNumber EcouponNumber { get; set; }
    }
}
