//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cgm.Ecoupon.Infrastructure.Persistence.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfferAutoPayDiscountDetail
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> CompanyId { get; set; }
        public Nullable<System.Guid> BranchId { get; set; }
        public Nullable<System.Guid> DivisionId { get; set; }
        public Nullable<System.Guid> TownshipId { get; set; }
        public Nullable<System.Guid> CityId { get; set; }
        public Nullable<System.Guid> DistrictId { get; set; }
        public Nullable<System.Guid> ProductGroupId { get; set; }
        public string SafetyCashierNumber { get; set; }
        public string AdanceMerchantNumber { get; set; }
        public string OkMobileWalletNumber { get; set; }
        public Nullable<int> CashBackSetting { get; set; }
        public Nullable<int> OfferAutoLoad { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<double> AutoPayDiscountPercentage { get; set; }
        public Nullable<double> AutoPayDiscountFixed { get; set; }
        public Nullable<double> AutoPayDiscountRatio { get; set; }
        public Nullable<double> MinimumAmount { get; set; }
        public Nullable<double> MaximumAmount { get; set; }
        public Nullable<double> CashbackAmount { get; set; }
        public bool IsActive { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual BranchDetail BranchDetail { get; set; }
        public virtual City City { get; set; }
        public virtual CompanyDetail CompanyDetail { get; set; }
        public virtual District District { get; set; }
        public virtual Division Division { get; set; }
        public virtual ProductGroupDetail ProductGroupDetail { get; set; }
        public virtual TownShip TownShip { get; set; }
    }
}
