//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cgm.Ecoupon.Infrastructure.Persistence.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfferDisplayAppVersionDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OfferDisplayAppVersionDetail()
        {
            this.OfferDisplayAppVersionDetailsHistories = new HashSet<OfferDisplayAppVersionDetailsHistory>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid OfferDisplayDetailsId { get; set; }
        public System.Guid OfferOsDetailsId { get; set; }
        public bool IsActive { get; set; }
        public int TrackSeqNo { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual OfferDisplayDetail OfferDisplayDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OfferDisplayAppVersionDetailsHistory> OfferDisplayAppVersionDetailsHistories { get; set; }
    }
}
