//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cgm.Ecoupon.Infrastructure.Persistence.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfferConfiguration
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OfferConfiguration()
        {
            this.OfferConfigurationMobileNumberDetails = new HashSet<OfferConfigurationMobileNumberDetail>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid OfferListingTypeId { get; set; }
        public System.Guid CompanyId { get; set; }
        public System.Guid DivisionId { get; set; }
        public System.Guid TownShipId { get; set; }
        public System.Guid CityId { get; set; }
        public System.Guid DistrictId { get; set; }
        public System.Guid BranchId { get; set; }
        public System.Guid OfferBackendNumberId { get; set; }
        public bool IsActive { get; set; }
        public int ApprovalReqFlag { get; set; }
        public Nullable<System.DateTime> ApprovalReqDateTime { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual BranchDetail BranchDetail { get; set; }
        public virtual City City { get; set; }
        public virtual CompanyDetail CompanyDetail { get; set; }
        public virtual District District { get; set; }
        public virtual Division Division { get; set; }
        public virtual OfferBackendNumber OfferBackendNumber { get; set; }
        public virtual OfferListingType OfferListingType { get; set; }
        public virtual TownShip TownShip { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OfferConfigurationMobileNumberDetail> OfferConfigurationMobileNumberDetails { get; set; }
    }
}
