//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cgm.Ecoupon.Infrastructure.Persistence.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfferConfigurationMobileNumberDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OfferConfigurationMobileNumberDetail()
        {
            this.OfferConditionalMappingCustomerDetails = new HashSet<OfferConditionalMappingCustomerDetail>();
            this.OfferDisplayMappingDetails = new HashSet<OfferDisplayMappingDetail>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid OfferConfigurationId { get; set; }
        public Nullable<System.Guid> BranchMobileNumberId { get; set; }
        public string SenderName { get; set; }
        public string SenderMobileNumber { get; set; }
        public string SafetyCashierName { get; set; }
        public string SafetyCashierMobileNumber { get; set; }
        public bool IsActive { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual BranchMobileNumberDetail BranchMobileNumberDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OfferConditionalMappingCustomerDetail> OfferConditionalMappingCustomerDetails { get; set; }
        public virtual OfferConfiguration OfferConfiguration { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OfferDisplayMappingDetail> OfferDisplayMappingDetails { get; set; }
    }
}
