//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cgm.Ecoupon.Infrastructure.Persistence.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.OfferApprovalSetups = new HashSet<OfferApprovalSetup>();
            this.UserAccessRights = new HashSet<UserAccessRight>();
            this.UserOfferTypeDetails = new HashSet<UserOfferTypeDetail>();
            this.UserProductGroupDetails = new HashSet<UserProductGroupDetail>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid UserTypeId { get; set; }
        public System.Guid CompanyId { get; set; }
        public string UserLoginId { get; set; }
        public string UserPassword { get; set; }
        public bool UserFirstTimeFlag { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string MobileNumber { get; set; }
        public string EmailId { get; set; }
        public string UserPhoto { get; set; }
        public string Otp { get; set; }
        public Nullable<System.DateTime> OtpExpireDateTime { get; set; }
        public bool ApprovalUserFlag { get; set; }
        public bool RememberMe { get; set; }
        public Nullable<System.DateTime> LastLoginDateTime { get; set; }
        public bool IsActive { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual CompanyDetail CompanyDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OfferApprovalSetup> OfferApprovalSetups { get; set; }
        public virtual UserType UserType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserAccessRight> UserAccessRights { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserOfferTypeDetail> UserOfferTypeDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserProductGroupDetail> UserProductGroupDetails { get; set; }
    }
}
