//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cgm.Ecoupon.Infrastructure.Persistence.Data
{
    using System;
    
    public partial class GetAssignOfferDetails_Result
    {
        public string Division { get; set; }
        public string District { get; set; }
        public string Township { get; set; }
        public string City { get; set; }
        public string ProductGroupName { get; set; }
        public string OkAccountNumber { get; set; }
        public string OkAccountType { get; set; }
        public string OfferTypeName { get; set; }
        public string OfferName { get; set; }
        public int OfferAmount { get; set; }
        public int OfferDiscountAmount { get; set; }
        public int TotalCount { get; set; }
        public string OfferBase { get; set; }
        public System.DateTime CreatedDate { get; set; }
    }
}
