//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cgm.Ecoupon.Infrastructure.Persistence.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BranchMobileNumberDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BranchMobileNumberDetail()
        {
            this.OfferBlockBranchDetails = new HashSet<OfferBlockBranchDetail>();
            this.OfferConditiionalMappingBranchDetails = new HashSet<OfferConditiionalMappingBranchDetail>();
            this.OfferConfigurationMobileNumberDetails = new HashSet<OfferConfigurationMobileNumberDetail>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid BranchId { get; set; }
        public string BranchReceiverName { get; set; }
        public string BranchReceiverMobileNumber { get; set; }
        public bool IsActive { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual BranchDetail BranchDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OfferBlockBranchDetail> OfferBlockBranchDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OfferConditiionalMappingBranchDetail> OfferConditiionalMappingBranchDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OfferConfigurationMobileNumberDetail> OfferConfigurationMobileNumberDetails { get; set; }
    }
}
