//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cgm.Ecoupon.Infrastructure.Persistence.Data
{
    using System;
    
    public partial class GetOverAmountNoDiscount_Result
    {
        public string CompanyName { get; set; }
        public string OfferAssignmentBranch { get; set; }
        public string ProductGroup { get; set; }
        public string OfferType { get; set; }
        public string OfferCode { get; set; }
        public string OfferName { get; set; }
        public int PromotionAmount { get; set; }
        public int NoDiscountAmount { get; set; }
        public int TransactionAmount { get; set; }
        public string OkAccountType { get; set; }
        public string OkAccountNumber { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public decimal Latitude { get; set; }
        public decimal Longitude { get; set; }
        public string LocationAddressMap { get; set; }
    }
}
