//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cgm.Ecoupon.Infrastructure.Persistence.Data
{
    using System;
    
    public partial class GetAutoPayReport_Result
    {
        public Nullable<long> No { get; set; }
        public string OkDebitWalletNumber { get; set; }
        public string SenderMobileNumber { get; set; }
        public string SenderDivision { get; set; }
        public string SenderDistrict { get; set; }
        public string SenderTownship { get; set; }
        public string SenderCity { get; set; }
        public int BeforeDiscountAmount { get; set; }
        public int AfterDiscountAmount { get; set; }
        public string SafetyCashierNumber { get; set; }
        public Nullable<double> AutoPayDiscount { get; set; }
        public Nullable<double> AutoPayFixed { get; set; }
        public Nullable<double> AutoPayRatio { get; set; }
        public string OSType { get; set; }
        public decimal OSVersion { get; set; }
        public decimal OkDollarVersion { get; set; }
        public decimal Latitude { get; set; }
        public decimal Longitude { get; set; }
        public string LocationAdress { get; set; }
        public System.DateTime DateTime { get; set; }
    }
}
