//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cgm.Ecoupon.Infrastructure.Persistence.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfferTermsAndConditionHistory
    {
        public System.Guid Id { get; set; }
        public System.Guid OfferTermsAndConditionId { get; set; }
        public System.Guid OfferDetailsId { get; set; }
        public bool ConditionalFlag { get; set; }
        public bool NonConditionalFlag { get; set; }
        public int PerDayCount { get; set; }
        public string DayNameList { get; set; }
        public System.DateTime StartDateTime { get; set; }
        public System.DateTime EndDateTime { get; set; }
        public string OfferRedemType { get; set; }
        public Nullable<int> OfferRedemCount { get; set; }
        public Nullable<decimal> OfferRedemAmount { get; set; }
        public Nullable<decimal> OfferRedemMinimumAmount { get; set; }
        public Nullable<decimal> OfferRedemMaximumAmount { get; set; }
        public int OfferTermsAndConditionTrackingSeqNo { get; set; }
        public bool IsActive { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
