//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cgm.Ecoupon.Infrastructure.Persistence.Data
{
    using System;
    
    public partial class GetOfferCountOfferTypeWise_Result
    {
        public string OfferListingName { get; set; }
        public Nullable<int> OfferCount { get; set; }
    }
}
