//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cgm.Ecoupon.Infrastructure.Persistence.Data
{
    using System;
    
    public partial class GetTodayTotalOkDollarOfferRedeemCount_Result
    {
        public Nullable<int> TotalOfferRedeemCount { get; set; }
        public Nullable<int> TotalAndroidVersionOfferRedeemCount { get; set; }
        public Nullable<int> TotalIOSVersionOfferRedeemCount { get; set; }
        public Nullable<int> TotalOfferBranch { get; set; }
        public Nullable<int> TotalOfferAmountDiscount { get; set; }
        public Nullable<int> TotalOfferTypeCount { get; set; }
        public Nullable<int> TotalOfferTransactionCount { get; set; }
        public int TotalPercentageBaseOfferCount { get; set; }
        public int TotalAmountBaseOfferCount { get; set; }
        public int TotalOkPersonalAccountOfferRedeemCount { get; set; }
        public int TotalOkMerchantAccountOfferRedeemCount { get; set; }
        public int TotalOkAdvanceMerchantAccountOfferRedeemCount { get; set; }
        public int TotaOkAgentAccountOfferRedeemCount { get; set; }
    }
}
